apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oebs-fullmakt-godkjenning-api-q1
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  image: {{ image }}
  port: 8080

  envFrom:
    - secret: oebs-fullmakt-godkjenning-q1

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java

  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/isalive
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isready
    initialDelay: 60
    timeout: 10
  resources:
    requests:
      cpu: 50m
      memory: 384Mi
    limits:
      memory: 384Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true

  prometheus:
    enabled: true
    path: /actuator/prometheus

  ingresses:
    - "https://oebs-fullmakt-godkjenning-api-q1.intern.dev.nav.no"