apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: oebs-fullmakt-godkjenning-api
  namespace: team-oebs
  labels:
    team: team-oebs
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/isalive
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isready
    initialDelay: 60
    timeout: 11
  resources:
    requests:
      cpu: 400m
      memory: 1024Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  azure:
    application:
      enabled: true
      allowAllUsers: true

  prometheus:
    enabled: true
    path: /actuator/prometheus
  vault:
    enabled: true
    paths:
      - kvPath: "kv/prod/fss/oebs-fullmakt-godkjenning-api/team-oebs"
        mountPath: "/var/run/secrets/nais.io/vault"

  ingresses:
     - "https://oebs-fullmakt-godkjenning-api.intern.nav.no"